# Generated by Django 4.2.8 on 2024-02-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_bus_alter_buslocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='password',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='bus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.bus'),
        ),
    ]
