# Generated by Django 4.2.8 on 2024-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_bus_name_bus_password_alter_buslocation_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
