# Generated by Django 4.2.8 on 2024-03-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_alter_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_location', models.CharField(choices=[('clt', 'CLT'), ('hostel', 'Hostel'), ('bhoopali', 'Bhoopali')], max_length=10)),
                ('to_location', models.CharField(choices=[('clt', 'CLT'), ('hostel', 'Hostel'), ('bhoopali', 'Bhoopali')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.bus')),
            ],
        ),
    ]
