# Generated by Django 4.2.8 on 2024-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_id',
            field=models.IntegerField(default=0),
        ),
    ]
