# Generated by Django 4.2.8 on 2024-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0006_schedule_day_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_id',
            field=models.IntegerField(),
        ),
    ]
